### ISSUE TITLE
missing config.monitoring file

### ISSUE THREAD

**Issue by edsiper** [vegasbrianc/docker-pulls#1]
when starting the repo with docker-compose up, the following error is raised:

```
ERROR: Couldn't find env file: /home/edsiper/coding/docker-pulls/config.monitoring
```

**Comment by vegasbrianc** [comment]
Hi @edsiper Thanks for letting me know. I have added the config.monitoring file. If anything else is missing you can let me know or check the https://github.com/vegasbrianc/prometheus which is what this project is based from.
